<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto

namespace GPBMetadata;

class Search
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aef010a0c7365617263682e70726f746f224c0a0d53656172636852657175657374120d0a05717565727918012001280912130a0b706167655f6e756d62657218022001280512170a0f726573756c745f7065725f70616765180320012805224d0a0e536561726368526573706f6e7365120d0a05717565727918012001280912130a0b706167655f6e756d62657218022001280512170a0f726573756c745f7065725f70616765180320012805323a0a0d5365617263685365727669636512290a06536561726368120e2e536561726368526571756573741a0f2e536561726368526573706f6e7365620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

